apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-project-kubequest-frontend-cert
  namespace: dev-project-kubequest-frontend
spec:
  secretName: dev-project-kubequest-frontend-tls
  dnsNames:
    - dev.kubequest.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
