apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-project-kubequest-frontend-cert
  namespace: staging-project-kubequest-frontend
spec:
  secretName: staging-project-kubequest-frontend-tls
  dnsNames:
    - staging.kubequest.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
