apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-project-kubequest-frontend-cert
  namespace: prod-project-kubequest-frontend
spec:
  secretName: prod-project-kubequest-frontend-tls
  dnsNames:
    - kubequest.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
