apiVersion: v1
kind: Service
metadata:
  name: prod-project-kubequest-frontend-service
  namespace: prod-project-kubequest-frontend
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: prod-project-kubequest-frontend
